### ISSUE TITLE
failed to run custom build command for server-core

### ISSUE THREAD

**Issue by harshasrisri** [nokia/memory-profiler#11]
Hey,
Ran into this panic when building memory-profiler-cli on Linux with rust nightly.

```
error: failed to run custom build command for `server-core v0.1.0 (/home/harshasrisri/Code/memory-profiler/server-core)`
process didn't exit successfully: `/home/harshasrisri/Code/memory-profiler/target/release/build/server-core-436551ca2cd1c07d/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'cannot launch a child process to install the dependencies for the WebUI: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/libcore/macros.rs:18
   9: semalock::Semalock::with
             at /rustc/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/libcore/result.rs:827
             at server-core/build.rs:50
             at /home/harshasrisri/.cargo/registry/src/github.com-1ecc6299db9ec823/semalock-0.2.0/src/lib.rs:99
             at /rustc/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/libcore/result.rs:639
             at /home/harshasrisri/.cargo/registry/src/github.com-1ecc6299db9ec823/semalock-0.2.0/src/lib.rs:96
  10: build_script_build::main
             at server-core/build.rs:46
  11: std::rt::lang_start::{{closure}}
             at /rustc/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: main
  16: __libc_start_main
  17: _start

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by koute** [comment]
This might be a silly question, but do you have `yarn` installed?

**Comment by mcsalim55** [comment]
Hi please help you

**Comment by harshasrisri** [comment]
@koute That fixed it. Thank you. 
I didn't have it installed earlier. But after installing it, the build completed successfully.
