### ISSUE TITLE
webui fails to install `deasync` when nodejs >= v11

### ISSUE THREAD

**Issue by cengizIO** [nokia/memory-profiler#6]
Hello,

I have nodejs `v11.15.0` and yarn `v1.16.0` on ArchLinux.
yarn install fails:
```
% cargo build --release -p memory-profiler-cli
   Compiling server-core v0.1.0 (/opt/memory-profiler/server-core)
error: failed to run custom build command for `server-core v0.1.0 (/opt/memory-profiler/server-core)`

Caused by:
  process didn't exit successfully: `/opt/memory-profiler/target/release/build/server-core-f10adbcb2301933b/build-script-build` (exit code: 101)
--- stdout
yarn install v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

--- stderr
error /opt/memory-profiler/webui/node_modules/deasync: Command failed.
Exit code: 1
Command: node ./build.js
Arguments: 
Directory: /opt/memory-profiler/webui/node_modules/deasync
Output:
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:253:12)
    at onErrorNT (internal/child_process.js:429:16)
    [... lines matching original stack trace ...]
    at internal/main/run_main_module.js:21:11
thread 'main' panicked at 'Failed to install the dependencies for the WebUI; child process exited with error code Some(1)! You might want to try to run 'rm -Rf ~/.cache/yarn' and try again.', server-core/build.rs:61:21
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I've checked `deasync` repository for related issues and tried upgrading it to `0.1.15` by following changes

```diff
diff --git a/webui/package.json b/webui/package.json
index a955aee..7640d78 100644
--- a/webui/package.json
+++ b/webui/package.json
@@ -17,6 +17,7 @@
   "dependencies": {
     "bootstrap": "^4.1.1",
     "bootswatch": "^4.1.1",
+    "deasync": "^0.1.15",
     "dygraphs": "^2.1.0",
     "feather-icons": "^4.7.3",
     "font-awesome": "^4.7.0",
diff --git a/webui/yarn.lock b/webui/yarn.lock
index d4b879a..7728097 100644
--- a/webui/yarn.lock
+++ b/webui/yarn.lock
@@ -1386,12 +1386,13 @@ date-now@^0.1.4:
   version "0.1.4"
   resolved "https://registry.yarnpkg.com/date-now/-/date-now-0.1.4.tgz#eaf439fd4d4848ad74e5cc7dbef200672b9e345b"
 
-deasync@^0.1.13:
-  version "0.1.13"
-  resolved "https://registry.yarnpkg.com/deasync/-/deasync-0.1.13.tgz#815c2b69bbd1117cae570152cd895661c09f20ea"
+deasync@^0.1.13, deasync@^0.1.15:
+  version "0.1.15"
+  resolved "https://registry.yarnpkg.com/deasync/-/deasync-0.1.15.tgz#788c4bbe6d32521233b28d23936de1bbadd2e112"
+  integrity sha512-pxMaCYu8cQIbGkA4Y1R0PLSooPIpH1WgFBLeJ+zLxQgHfkZG86ViJSmZmONSjZJ/R3NjwkMcIWZAzpLB2G9/CA==
   dependencies:
     bindings "~1.2.1"
-    nan "^2.0.7"
+    node-addon-api "^1.6.0"
 
 debug@2.6.9, debug@^2.1.2, debug@^2.2.0, debug@^2.3.3, debug@^2.6.8, debug@^2.6.9:
   version "2.6.9"
@@ -2575,7 +2576,7 @@ ms@2.0.0:
   version "2.0.0"
   resolved "https://registry.yarnpkg.com/ms/-/ms-2.0.0.tgz#5608aeadfc00be6c2901df5f9861788de0d597c8"
 
-nan@^2.0.7, nan@^2.9.2:
+nan@^2.9.2:
   version "2.11.0"
   resolved "https://registry.yarnpkg.com/nan/-/nan-2.11.0.tgz#574e360e4d954ab16966ec102c0c049fd961a099"
 
@@ -2607,6 +2608,11 @@ nice-try@^1.0.4:
   version "1.0.5"
   resolved "https://registry.yarnpkg.com/nice-try/-/nice-try-1.0.5.tgz#a3378a7696ce7d223e88fc9b764bd7ef1089e366"
 
+node-addon-api@^1.6.0:
+  version "1.6.3"
+  resolved "https://registry.yarnpkg.com/node-addon-api/-/node-addon-api-1.6.3.tgz#3998d4593e2dca2ea82114670a4eb003386a9fe1"
+  integrity sha512-FXWH6mqjWgU8ewuahp4spec8LkroFZK2NicOv6bNwZC3kcwZUI8LeZdG80UzTSLLhK4T7MsgNwlYDVRlDdfTDg==
+
 node-fetch@^1.0.1:
   version "1.7.3"
   resolved "https://registry.yarnpkg.com/node-fetch/-/node-fetch-1.7.3.tgz#980f6f72d85211a5347c6b2bc18c5b84c3eb47ef"
```
After changes in `yarn.lock` and `packages.json`, `yarn add deasync` succeeds.

Now the dependency installation finishes without exceptions.

**Comment by koute** [comment]
This is interesting. I'm also running Arch, with Node `11.15.0` and Yarn `1.16.0`, and I can't reproduce this - everything builds correctly on my machine.

I'm fine with merging this though; could you perhaps create a PR with your fix? (Although I think it's not necessary to add the `deasync` dependency to `package.json` - it should be enough to only update the `.lock` file.)
